image: uhub.service.ucloud.cn/org_bdks4e/node:12.22.1

stages:
    - build

pages:
    stage: build
    before_script:
        - apt-get install autoconf automake libtool git
    script:
        - git clone https://github.com/UCloud-FE/react-components.git react-components
        - cd react-components && npm install && npm run build:recodo && cp ./.recodo/data/* ../content/ && cd ..
        - npm install
        - npm run build -- --prefix-paths
    # cache:
    #   key:
    #     files:
    #       - package-lock.json
    #       - package.json
    #     prefix: $CI_PROJECT_NAME-$CI_JOB_NAME
    #   paths:
    #     - node_modules/
    artifacts:
        paths:
            - public
    only: ['master', 'dev']
    tags:
        - uaek-c1
